### ISSUE TITLE
Someone skidded your grabber 

### ISSUE THREAD

**Issue by pancak3boy** [Smug246/Luna-Token-Grabber#104]
theres this guy who skidded ur grabber and put it on github AND HES ALSO SELLING SOME OF ITS FEATURES. blackcap grabber is the name go check it out hes such a skid omfg

**Comment by KDot227** [comment]
💀

**Comment by Smug246** [comment]
> theres this guy who skidded ur grabber and put it on github AND HES ALSO SELLING SOME OF ITS FEATURES. blackcap grabber is the name go check it out hes such a skid omfg

ye i've seen it. not a lot i can do tbh

**Comment by Kyxnite** [comment]
pancake you gay skid
