### ISSUE TITLE
To do for smug or maybe idk smd

### ISSUE THREAD

**Issue by KDot227** [Smug246/Luna-Token-Grabber#105]
1.) add file pumper
2.) idk if u got default icon option
3.) ill add more when home

**Comment by Smug246** [comment]
> 1.) add file pumper
> 
> 2.) idk if u got default icon option
> 
> 3.) ill add more when home

ye im probs gonna add a default one and file pumper/dead code ye

**Comment by KDot227** [comment]
> > 1.) add file pumper
> > 2.) idk if u got default icon option
> > 3.) ill add more when home
> 
> ye im probs gonna add a default one and file pumper/dead code ye

did I send u code for file pumper yet ion remember

**Comment by Smug246** [comment]
nah i made one myself
