### ISSUE TITLE
This version is up to date!

### ISSUE THREAD

**Issue by kadirmerfs** [Smug246/Luna-Token-Grabber#107]
This version is up to date! i am getting this error

**Comment by Smug246** [comment]
if it's saying that you need an update download the latest version.

**Comment by kadirmerfs** [comment]
i solved but its not grab chrome password just grab cookie cc's and history can you add password

**Comment by Smug246** [comment]
it couldnt find any passwords then

**Comment by Smug246** [comment]
latest version
