### ISSUE TITLE
roblox token dont work

### ISSUE THREAD

**Issue by edeiber441** [Smug246/Luna-Token-Grabber#110]
roblox token dont work pls help

**Comment by Smug246** [comment]
wdym?

**Comment by edeiber441** [comment]
when i build a .exe with the configuration of roblox token it send a document to my discord but have nothing

**Comment by edeiber441** [comment]
and im logged in roblox

**Comment by Smug246** [comment]
go into the cookies.txt and search roblox and tell me if its there

**Comment by edeiber441** [comment]
no

**Comment by shitweenie13** [comment]
.roblosecurity is always in cookies.txt for me, all you have to do to log in with it is use a cookie refresher and put it in editthiscookie

**Comment by Smug246** [comment]
> .roblosecurity is always in cookies.txt for me, all you have to do to log in with it is use a cookie refresher and put it in editthiscookie

ye thats how i extract the roblox cookie anyways so if its not there then i cant do anything for you

**Comment by Huxultor** [comment]
BlackCap Cookie Logger Work better

**Comment by Smug246** [comment]
> .roblosecurity is always in cookies.txt for me, all you have to do to log in with it is use a cookie refresher and put it in editthiscookie

fully fixed now. download latest version
