### ISSUE TITLE
CC Grabber does not work

### ISSUE THREAD

**Issue by mass-leak** [Smug246/Luna-Token-Grabber#112]
Hey smug, Thank you for your work, all works well. However the CC grabber doesn't seem to work, any ideas?
I've tried it on multiple pcs with cc's on chrome/opera/ etc

**Comment by Smug246** [comment]
is the problem that the file is empty or there's no file

**Comment by mass-leak** [comment]
The file is always completely empty

> is the problem that the file is empty or there's no file

**Comment by Smug246** [comment]
closing as this was resolved on discord
