### ISSUE TITLE
Self destruct might not work in case of executable file

### ISSUE THREAD

**Issue by Blank-c** [Smug246/Luna-Token-Grabber#114]
The `__file__` variable is the path to the _source file_. But when it is packed with pyinstaller, this path does not work anymore. To get the path of exe, you need to use `sys.executable` variable.

Further, when you run the source file, its read instantly and then executed. The file is not locked in any way. But in case of executable files, they are locked by the subprocess. Hence, you cannot call `os.remove()` on them.

If you want it to self destruct, you need to make another program delete it, or I should say, you need to use the delete command after the exe is finished running.

**Comment by Smug246** [comment]
whats the delete command?

**Comment by Blank-c** [comment]
[Here](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/main.py#L109-L116) you can see how Blank Grabber handle this.

**Comment by Smug246** [comment]
oh ok thanks. @Blank-c before i got termed you sent me loads of things to add to my script. Could you create another issue for enhancements as I've forgotten the rest of what u said

**Comment by Blank-c** [comment]
You can see the code and think what can I do instead of this. Then you will get your answer

**Comment by Smug246** [comment]
helpful
