### ISSUE TITLE
Cant Build exe or py file

### ISSUE THREAD

**Issue by BridgeKeeper1** [Smug246/Luna-Token-Grabber#115]
When i try to build a py or exe file it doesn't work pls help

**Comment by Smug246** [comment]
are u getting any errors?

**Comment by Huxultor** [comment]
Try to use BlackCap

**Comment by BridgeKeeper1** [comment]
no

**Comment by Smug246** [comment]
is there a logs.txt

**Comment by BridgeKeeper1** [comment]
no

**Comment by Smug246** [comment]
what python version do you have

**Comment by BridgeKeeper1** [comment]
3.11

**Comment by Smug246** [comment]
try running it in cmd from the files directory and tell me what it says

**Comment by TenZ-XD** [comment]
> is there a [WinError 2] The system cannot find the file specified: '.\\Obfuscated_test .py' -> '.\\test .py'

**Comment by Smug246** [comment]
do you enable the obfuscate checkbox?

**Comment by TenZ-XD** [comment]
![image](https://user-images.githubusercontent.com/100017281/216822858-dc259695-0f9a-49be-82a7-41b303751e3b.png)
![Screenshot 2023-02-05 191412](https://user-images.githubusercontent.com/100017281/216822868-313e22f3-f851-4e58-a4d8-8f82fb2b43be.png)

**Comment by Smug246** [comment]
fixed in another issue

**Comment by BridgeKeeper1** [comment]
still doesnt work for me

**Comment by ULAN631** [comment]
i cant build on luna , i press build but nothing happens
