### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by YangerOne6** [Smug246/Luna-Token-Grabber#118]
![image](https://user-images.githubusercontent.com/122757604/216478867-d266cc97-2ec8-453b-96dd-039ec216c48b.png)
im here but when i click build nothing happens. no error.

**Comment by BridgeKeeper1** [comment]
Same

**Comment by Blank-c** [comment]
open cmd in the builder's directory and type `py builder.pyw`, then click on build and check to see if there is some error raised in CMD

**Comment by Smug246** [comment]
no reply so closing
