### ISSUE TITLE
Building Issue #2

### ISSUE THREAD

**Issue by Drewwwe** [Smug246/Luna-Token-Grabber#119]
It shows this error:
![Captur](https://user-images.githubusercontent.com/117297205/216786999-d9dbfc78-53b0-4386-9b8e-15be43e6b40f.PNG)

**Comment by Smug246** [comment]
what os are you trying to build it on?. It seems like you need to download the bootloader yourself. You can look at the docs for that here https://pyinstaller.org/en/stable/bootloader-building.html

**Comment by KDot227** [comment]
> what os are you trying to build it on?. It seems like you need to download the bootloader yourself. You can look at the docs for that here https://pyinstaller.org/en/stable/bootloader-building.html

3.11 issue I think

**Comment by Smug246** [comment]
> > what os are you trying to build it on?. It seems like you need to download the bootloader yourself. You can look at the docs for that here https://pyinstaller.org/en/stable/bootloader-building.html
> 
> 3.11 issue I think

works fine for me on 3.11

**Comment by SSJB-Hax** [comment]
Can someone help me :How do i use the luna grabber on other people it only displays information of me even when i use a webhook created by someone else it displays info only about me.

**Comment by Smug246** [comment]
send it to someone else lmao
