### ISSUE TITLE
Obfuscation Issue

### ISSUE THREAD

**Issue by TenZ-XD** [Smug246/Luna-Token-Grabber#121]
[WinError 2] The system cannot find the file specified: '.\\Obfuscated_test .py' -> '.\\test .py' 
![image](https://user-images.githubusercontent.com/100017281/216822740-ff600798-bde6-4cfc-8dc2-2df216cfa946.png)

**Comment by Smug246** [comment]
do you enable the obfuscate checkbox?

**Comment by TenZ-XD** [comment]
> do you enable the obfuscate checkbox?

![image](https://user-images.githubusercontent.com/100017281/216822943-4df9b2f0-c2e8-4eb4-bc58-3e6364ed72d4.png)

**Comment by Smug246** [comment]
can you go to your cmd and run the command `python -V` and tell me what it says

**Comment by TenZ-XD** [comment]
> can you go to your cmd and run the command `python -V` and tell me what it says

![py](https://user-images.githubusercontent.com/100017281/216823314-03502d5d-286b-4d7b-8446-8fbf69e7a520.png)

**Comment by TenZ-XD** [comment]
aha it's coz my py version is 3.10 but req. is 3.11

**Comment by Smug246** [comment]
ye download latest and try that

**Comment by Smug246** [comment]
@TenZ-XD lmk if it works so i can close the ticket

**Comment by TenZ-XD** [comment]
> @TenZ-XD lmk if it works so i can close the ticket

yha official site is in Maintenace once it's completed i will let u know

**Comment by Smug246** [comment]
what
