### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Loko415** [Smug246/Luna-Token-Grabber#16]
failed to run script google-passwords not found

**Comment by Smug246** [comment]
> failed to run script google-passwords not found

i've just realised a pushed a commit that doesn't work. i'll have that fixed later on when i get back

**Comment by Smug246** [comment]
try now

**Comment by Loko415** [comment]
hey bud. You should setup a vm and try yourself. I mean i can try it but it would be better if you had your own test enviroment. good work by the way

**Comment by Smug246** [comment]
> hey bud. You should setup a vm and try yourself. I mean i can try it but it would be better if you had your own test enviroment. good work by the way
> 
> 

lmao i don't get that error. just u. that's why i didn't know i made the wrong commit. obviously i test them beforehand otherwise that would be useless.

**Comment by Harry989** [comment]
I would like to reopen this issue, because I am now getting this exact issue.
