### ISSUE TITLE
(Permission Error): 'Permission denied: 'Luna-Logged-*my_username*.zip

### ISSUE THREAD

**Issue by Raplhs** [Smug246/Luna-Token-Grabber#18]
I make the exe with a random name, ran it, but this error always pops up and the bot doesn't work.

<img width="310" alt="error" src="https://user-images.githubusercontent.com/103277643/183230580-7f1d0302-dff0-4ada-8942-9222efd8d68e.png">

Idk what's going on, my other issue ticket was with changed code, but Idk. Please fix, this is a major issue. :)

**Comment by GodFather227** [comment]
> I make the exe with a random name, ran it, but this error always pops up and the bot doesn't work.
> 
> <img alt="error" width="310" src="https://user-images.githubusercontent.com/103277643/183230580-7f1d0302-dff0-4ada-8942-9222efd8d68e.png">
> 
> Idk what's going on, my other issue ticket was with changed code, but Idk. Please fix, this is a major issue. :)

that means u have it open

**Comment by Smug246** [comment]
> I make the exe with a random name, ran it, but this error always pops up and the bot doesn't work.
> 
> 
> 
> <img width="310" alt="error" src="https://user-images.githubusercontent.com/103277643/183230580-7f1d0302-dff0-4ada-8942-9222efd8d68e.png">
> 
> 
> 
> Idk what's going on, my other issue ticket was with changed code, but Idk. Please fix, this is a major issue. :)
> 
> 

like k.dot said you opened it before it finished wait till it sends it to the webhook and download it from there

**Comment by Raplhs** [comment]
> > I make the exe with a random name, ran it, but this error always pops up and the bot doesn't work.
> > <img alt="error" width="310" src="https://user-images.githubusercontent.com/103277643/183230580-7f1d0302-dff0-4ada-8942-9222efd8d68e.png">
> > Idk what's going on, my other issue ticket was with changed code, but Idk. Please fix, this is a major issue. :)
> 
> like k.dot said you opened it before it finished wait till it sends it to the webhook and download it from there

Ohhhh. I had to run on desktop. I'm sorry about that, I should've used common sense lol. Thanks both of you for your time :)
