### ISSUE TITLE
disable script errors

### ISSUE THREAD

**Issue by Loko415** [Smug246/Luna-Token-Grabber#19]
if the script fails make it so it doesnt show the user. Openly says failed to grab passwords etc.

**Comment by Smug246** [comment]
wdym?

**Comment by Loko415** [comment]
![image](https://user-images.githubusercontent.com/67609719/183288779-5c42a403-a8d2-4f02-9d8a-3bc6bfae1215.png)

**Comment by Loko415** [comment]
these types of errors.

**Comment by Smug246** [comment]
it doesn't say that. there's a try extract decorator that continues to the next one if there's any error. the error in that image is something different because you tried to open it before it had finished

**Comment by Loko415** [comment]
what if they keep spam opening it

**Comment by Loko415** [comment]
then that error appears obviously giving it away

**Comment by Smug246** [comment]
it will just keep opening multiple terminals and log them multiple times

**Comment by Loko415** [comment]
if the person you log runs it and sees that when they open it before its done. thats what im trying to say lol how do you disable that image error
