### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by DarkSuffer01** [Smug246/Luna-Token-Grabber#20]
So this issue, It saids line 21 cannot import name 'Embed' from 'Discord' (unknown location)
![image](https://user-images.githubusercontent.com/107288467/183623912-16e936fd-7b22-4cd9-b1d2-1bd8ca239ae2.png)
Can anyone help me asap

**Comment by Smug246** [comment]
> cannot import name 'Embed' from 'Discord' (unknown location)

do you have the discord module installed. if not do 'pip install discord'. if that doesn't work then try moving the files into a different folder.
