### ISSUE TITLE
Cannot find specified file: google-passwords.txt

### ISSUE THREAD

**Issue by Harry989** [Smug246/Luna-Token-Grabber#25]
Currently trying to create the grabber file but when it is run I get this error

![image](https://user-images.githubusercontent.com/46330151/189491801-e2345199-95a7-4142-840e-7a26cc18a32a.png)

''Traceback (most recent call last):
  File "Test.py", line 843, in <module>
  File "Test.py", line 82, in Luna
  File "Test.py", line 54, in main
  File "Test.py", line 580, in zipup
  File "zipfile.py", line 1728, in write
  File "zipfile.py", line 502, in from_file
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'google-passwords.txt'''

**Comment by Smug246** [comment]
other people have had this error and fixed it by simply opening the .exe in a different directory. so try that. if not i got some debugging to do

**Comment by Harry989** [comment]
I’ll give that a go then, if it fixes it I will close this. If not we always love our debugging 😂

**Comment by Harry989** [comment]
Also, the Installer.bat file isn't in the repo anymore. not sure if it isn't needed or something but that is still in the README.md

**Comment by Smug246** [comment]
ye i havnt updated the readme. im making some changes. havnt looked at this project for a month

**Comment by Harry989** [comment]
I see, and I moved the .exe to my desktop and ran it there and I still got the same error. is it supposed to dump a bunch of files in the directory that it is ran in? When I run it, I get the desktop screenshot and whatnot files on my desktop where I run it

**Comment by kingbasel** [comment]
i have the same problem whats the fix ? @Smug246

**Comment by Smug246** [comment]
@Harry989 when you run it and the files are in ur current directory is there a google cookies and google history?

**Comment by Harry989** [comment]
I don’t think I even have google installed, I use Opera GX, maybe make it so that if it isn’t able to pull google data the entire script doesn’t halt?

**Comment by Smug246** [comment]
try the most recent version

**Comment by Harry989** [comment]
Alrighty, I’ll give it a look.

**Comment by Smug246** [comment]
did it work? @Harry989

**Comment by Harry989** [comment]
Currently my PC’s boot partition is fucked so allow me to fix that really quick 😂

**Comment by Harry989** [comment]
@Smug246 It is functioning now

**Comment by Smug246** [comment]
good

**Comment by Harry989** [comment]
Though I have noticed it hasn't sent the desktop screenshot through the webhook, and the Luna-Logged-user.zip is completely empty.
