### ISSUE TITLE
can you add a password stealer that supports opera, edge...?

### ISSUE THREAD

**Issue by Bleed-5468** [Smug246/Luna-Token-Grabber#30]

**Comment by Smug246** [comment]
yes in the future i will be adding it

**Comment by Bypassme** [comment]
> yes in the future i will be adding it

can you make it work on chromebooks using linux debian?

**Comment by Smug246** [comment]
> > yes in the future i will be adding it
> 
> can you make it work on chromebooks using linux debian?

i would try to implement this but i already know it would make the program very slow because its in python

**Comment by Smug246** [comment]
added this now so closing
