### ISSUE TITLE
Not working (build.bat crashing and showing weird error)

### ISSUE THREAD

**Issue by Gumbobrot** [Smug246/Luna-Token-Grabber#31]
opens build.bat 

_All dependencies already installed
Well
Window crashes and a second before it says a weird error_

opens builder.py

_the same as before happens again_

**any ideas for a simple fix?**

**Comment by Smug246** [comment]
i need u to run it in cmd and ss the error

**Comment by Gumbobrot** [comment]
Uh sorry, I got no better picture/screenshot, it's closing really fast! 

https://user-images.githubusercontent.com/96620548/190919004-9fa42ac8-0186-4a2a-b4c0-607f6cbcd391.mp4

![Screenshot_20220918-185259_Gallery](https://user-images.githubusercontent.com/96620548/190919008-5895aeb0-3e2f-46d1-897f-0d8867bb32de.jpg)

**Comment by Smug246** [comment]
lmao i can barely see whats going on there. run it in cmd and if you dont know how to do that. [how to open in cmd](https://www.indeed.com/career-advice/career-development/how-to-run-program-in-command-prompt#:~:text=Type%20%22start%20%5Bfilename.exe,program%20from%20the%20file%20path.)

**Comment by Gumbobrot** [comment]
![image](https://user-images.githubusercontent.com/96620548/190921619-dbf29abb-d1d6-41e4-8a84-b1fbc630d6e1.png)

**Comment by Smug246** [comment]
are you on mac because python has no certificates at all on there. this grabber doesn't work with mac

**Comment by Gumbobrot** [comment]
I am on a windows Laptop..

**Comment by Smug246** [comment]
oh. try and open this and tell me if it works [test](https://jsonip.com/)

**Comment by Smug246** [comment]
there is a easy fix for this you can quite simply go into the builder.py file and remove line 107 where it says `IP: {load(urlopen('https://jsonip.com/'))['ip']}`. this is just an aesthetic feature and doesnt mean anything

**Comment by Gumbobrot** [comment]
What do I have to open?

**Comment by Smug246** [comment]
blue writing that says test

**Comment by Gumbobrot** [comment]
kk one sec ima try

**Comment by Gumbobrot** [comment]
![image](https://user-images.githubusercontent.com/96620548/190921925-e767e811-0487-4e98-9950-f32217dc8d13.png)
so I have to jsut remove all that?

**Comment by Smug246** [comment]
line 107 only

**Comment by Gumbobrot** [comment]
thanks! I will try the grabber now!

**Comment by Gumbobrot** [comment]
So! Is there maybe an option that you can choose what you want to enable, like this:

Obfuscate? Y/N
Injection process? Y/N
System Information? Y/N
Browser data? Y/N
Fake Error? Y/N = y
Error Message? = {message here}

Because it is really annoying if you just want to grab someone one time or simply test the grabber and after that you have to reinstall whole Discord because of the injection and stuff like that.

**Comment by Gumbobrot** [comment]
And I just tried the grabber and after test executing it was showing me this error:

Traceback (most recent call last):
  File "XrynzInstaller.py", line 649, in <module>
  File "XrynzInstaller.py", line 75, in Luna
  File "XrynzInstaller.py", line 62, in main
  File "discord\webhook\sync.py", line 1028, in send
  File "discord\webhook\sync.py", line 297, in execute_webhook
  File "discord\webhook\sync.py", line 220, in request
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.1.value: Must be 1024 or fewer in length.


It also created the files (history, passwords and more) but I can see those things and I think it should send it through the webhook to me.

**Comment by Smug246** [comment]
someone else got this error. im working to fix it 

> And I just tried the grabber and after test executing it was showing me this error:
> 
> Traceback (most recent call last): File "XrynzInstaller.py", line 649, in File "XrynzInstaller.py", line 75, in Luna File "XrynzInstaller.py", line 62, in main File "discord\webhook\sync.py", line 1028, in send File "discord\webhook\sync.py", line 297, in execute_webhook File "discord\webhook\sync.py", line 220, in request discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In embeds.0.fields.1.value: Must be 1024 or fewer in length.
> 
> It also created the files (history, passwords and more) but I can see those things and I think it should send it through the webhook to me.

i need to fix this soon. it basically just means its trying to add too much to the embed field

**Comment by Gumbobrot** [comment]
Oh oh okay, thanks, and whats about my suggestion?

**Comment by Smug246** [comment]
> So! Is there maybe an option that you can choose what you want to enable, like this:
> 
> Obfuscate? Y/N Injection process? Y/N System Information? Y/N Browser data? Y/N Fake Error? Y/N = y Error Message? = {message here}
> 
> Because it is really annoying if you just want to grab someone one time or simply test the grabber and after that you have to reinstall whole Discord because of the injection and stuff like that.

well if they can do that by just opening the .py and not the .exe

**Comment by Smug246** [comment]
the .py doesnt inject anything

**Comment by Gumbobrot** [comment]
I mean the created file (the grabber) if it's not already there, it would be maybe cool if you add a option to enable injection process.

**Comment by Smug246** [comment]
ok maybe

**Comment by Smug246** [comment]
think we're done here
