### ISSUE TITLE
It doesn't work anymore (I need some help)

### ISSUE THREAD

**Issue by Bleed-5468** [Smug246/Luna-Token-Grabber#32]
![image](https://user-images.githubusercontent.com/75040901/190924637-bd1fa259-adf5-46e4-b06b-1ddcec5e9894.png)

**Comment by Bleed-5468** [comment]
@Smug246

**Comment by Smug246** [comment]
im fixing this as we speak

**Comment by Bleed-5468** [comment]
> im fixing this as we speak

let me know when u fix it pls :)

**Comment by Bleed-5468** [comment]
> give me 5 mins max

Ok, I'll be waiting

**Comment by Smug246** [comment]
latest version

**Comment by Bleed-5468** [comment]
your grabber does not send the password when I change the password now :/ (btw can you add something to get the token of the user who have been infected when he runs discord + add it to the startup?) I hope i'm not disturbing you mate ;)

**Comment by Smug246** [comment]
injection might be broke rn not sure. i didnt make it. and i might potentially do this
