### ISSUE TITLE
Error message...

### ISSUE THREAD

**Issue by schwungvoll** [Smug246/Luna-Token-Grabber#35]
Traceback (most recent call last):
  File "idkkdkkkkkk.py", line 684, in <module>
  File "idkkdkkkkkk.py", line 63, in Luna
  File "idkkdkkkkkk.py", line 55, in main
  File "idkkdkkkkkk.py", line 106, in __init__
  File "idkkdkkkkkk.py", line 302, in upload
  File "discord\webhook\sync.py", line 1028, in send
  File "discord\webhook\sync.py", line 297, in execute_webhook
  File "discord\webhook\sync.py", line 220, in request
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.

![image](https://user-images.githubusercontent.com/96620548/191984143-ae23660f-850a-4019-bf11-c628ca0ed29d.png)

**Is this a fake error or a real error?**

And also, it's not showing Epic Games and Minecraft information, Discord 2FA Codes and Wifi Passwords. The files are just empty..

**Comment by Smug246** [comment]
that just means it couldnt grab them. and its a real error. i thought i fixed it though

**Comment by Gumbobrot** [comment]
kk I'll try it tomorrow..

**Comment by Gumbobrot** [comment]
It's not showing the error anymore but also it's still not showing my Epic Games/Minecraft Data. It would be also good if you add a option that you can see the Discord Token and fix this that I see my Minecraft/Epic Games Stuff. Everything else is working fine.

But I also have another question. A few days ago you told me to fix my first bug that I reported with simply removing line 107. So I have to remove it everytime now. Is it still important and only a error I get or is it something everyone gets when using Luna. If everyone has this bug, it would be pretty cool if you could remove line 107 from the code.

**Comment by Gumbobrot** [comment]
Oh.. and I've just seen that at the information tab you said that Luna is already grabbing tokens (I was already wondering a bit why it's only sending some system information and not even showing Tokens, Wifi Pass, Epic Games and Minecraft Stuff.) Please fix this... because for now it looks like this..
![20220924_144538](https://user-images.githubusercontent.com/96620548/192098950-3da9c7a3-4a3c-4079-a10b-e6a83590484c.jpg)

**Comment by Smug246** [comment]
i mean you can remove the try_extract decorater and it will show the error for minecraft and epic games not working. and i'm not too sure about why token isn't being grabbed

**Comment by mpompos12** [comment]
> i mean you can remove the try_extract decorater and it will show the error for minecraft and epic games not working. and i'm not too sure about why token isn't being grabbed

can you send us the version before the latest update so we can test it?

**Comment by Smug246** [comment]
@schwungvoll try the most recent version. If that doesn't work reopen this ticket

**Comment by schwungvoll** [comment]
Thanks! I have school now, I will do it later or tomorrow.

**Comment by schwungvoll** [comment]
Nope, still not working, my friend keeps getting a weird error.

**Comment by schwungvoll** [comment]
@Smug246 I tried + my friend tried and it's not working... We both are getting really weird and large errors. When I arrive home I will send the error in here.
