### ISSUE TITLE
not logging all info

### ISSUE THREAD

**Issue by mpompos12** [Smug246/Luna-Token-Grabber#36]
when i run the grabber it grabs only my system info and sends the zip file but it doesen't send the tokens

**Comment by Smug246** [comment]
is there any error

**Comment by mpompos12** [comment]
> is there any error

no

**Comment by mpompos12** [comment]
> is there any error

it just sernd only system info and the zip nothing nmore nothing less

**Comment by mpompos12** [comment]
do use in the code any rdimo reposetory link? if you do the gihub has taken down rdimo or rdimo deleted his acount

**Comment by KDot227** [comment]
> do use in the code any rdimo reposetory link? if you do the gihub has taken down rdimo or rdimo deleted his acount

fr?!?!?!?!?!?!?

**Comment by mpompos12** [comment]
> > do use in the code any rdimo reposetory link? if you do the gihub has taken down rdimo or rdimo deleted his acount
> 
> fr?!?!?!?!?!?!?

actually his acc got flagged

**Comment by KDot227** [comment]
> > > do use in the code any rdimo reposetory link? if you do the gihub has taken down rdimo or rdimo deleted his acount
> 
> > 
> 
> > fr?!?!?!?!?!?!?
> 
> 
> 
> actually his acc got flagged

Ong?!?!?

**Comment by your-bestie** [comment]
WAIT IS THIS LEGIT?!??! NO WAY THIS IS LEGIT, I HAVE SEX WITH RDIMO EVERY DAY THIS IS HEART BREAKING :sob:

**Comment by SlepPoweredBy2** [comment]
so uh anything new?

**Comment by KDot227** [comment]
> so uh anything new?

Your having an error but if we don't know then we can't help

**Comment by Smug246** [comment]
aiwefghauighauiowghawg

**Comment by SlepPoweredBy2** [comment]
> aiwefghauighauiowghawg

shut up dumb biatch
