### ISSUE TITLE
use pyvenv so u dont pack everything you've downloaded with pip

### ISSUE THREAD

**Issue by KDot227** [Smug246/Luna-Token-Grabber#39]
use pyvenv so that doesn't happen + controlled environment and easier to use sometimes

**Comment by KDot227** [comment]
This will also make the exe size smaller in general

**Comment by KDot227** [comment]
also with this "python -m PyInstaller --onefile --noconsole -i NONE --distpath ./ .\\{filename}.py" Don't use -i NONE since you'll get more detections also have the pyinstaller bootloader (https://pyinstaller.org/en/stable/bootloader-building.html) build on their pc so you get waaaay less detections. On top of that don't use noconsole since that will give it more detections have the console hide itself in the file.

**Comment by KDot227** [comment]
on top of that if u want to change the icon to absolutely nothing u can go to where the image is in the src and just replace it (im 90% sure this will work)

**Comment by KDot227** [comment]
but besides that W grabber

**Comment by Smug246** [comment]
good suggestions. I'll look into to see if there true

**Comment by KDot227** [comment]
> 

they all true but maybe not changing the icon by replacing the existing one. Everything else is a fact tho

**Comment by KDot227** [comment]
on timmy being fat

**Comment by Blank-c** [comment]
> on top of that if u want to change the icon to absolutely nothing u can go to where the image is in the src and just replace it (im 90% sure this will work)

If you'd like to change the icon to nothing, just use `-i NONE` flag in pyinstaller

**Comment by Blank-c** [comment]
**Suggestion:** Don't care much about reducing detection if you want to keep your open source project active, it will only hold you back.

**Comment by Blank-c** [comment]
Even if you make it undetectable, people will use it and it will eventually get a lot of detections.

**Comment by Blank-c** [comment]
it will not stay undetected forever you know

**Comment by Blank-c** [comment]
I'd rather suggest you to focus on reducing size.

**Comment by Smug246** [comment]
i see where your coming from now. tbh i'm doing both. but a logger with too many detections is just useless so it will still be a focus

**Comment by Blank-c** [comment]
> i see where your coming from now. tbh i'm doing both. but a logger with too many detections is just useless so it will still be a focus

Ok if you think so

**Comment by KDot227** [comment]
> Even if you make it undetectable, people will use it and it will eventually get a lot of detections.

when everyone is building their own unique bootloader it doesn't use the preinstalled one that comes with the pyinstaller pip package which greatly reduces the detections. All around its a good thing to add and some other grabbers even use this method.

**Comment by Blank-c** [comment]
Building bootloader require c compiler like mingw or msvc, I don't think everyone must have one and it would be an overhead to download.

**Comment by Blank-c** [comment]
I personally have given pyinstaller with precompiled bootloader with my grabber

**Comment by KDot227** [comment]
> Building bootloader require c compiler like mingw or msvc, I don't think everyone must have one and it would be an overhead to download.

It's not very hard to download one onto their computer and have it compile the code

**Comment by KDot227** [comment]
> I personally have given pyinstaller with precompiled bootloader with my grabber

Ok? It's still bad lmao

**Comment by Blank-c** [comment]
> > Building bootloader require c compiler like mingw or msvc, I don't think everyone must have one and it would be an overhead to download.
> 
> It's not very hard to download one onto their computer and have it compile the code

Its ok if you want, I am not forcing anyone. I just think its an overhead to do so.

**Comment by Blank-c** [comment]
> > I personally have given pyinstaller with precompiled bootloader with my grabber
> 
> Ok? It's still bad lmao

What is the "It"?

**Comment by KDot227** [comment]
> > > I personally have given pyinstaller with precompiled bootloader with my grabber
> > 
> > 
> > Ok? It's still bad lmao
> 
> What is the "It"?

preinstalled pyinstaller bootloader. Smug can do whatever he wants I'm just giving him suggestions on how to make it generally less detected. With regular pyinstaller if u compile a hello world py file it's still going to get something like 17 detections on virus total. If you use bootloader u can get about 9 if you're lucky. That is 8 fewer detections (basically half). Kids are still dumb and will run whatever they're sent I'm just saying it's better to have a lower detection if he has the power to do it.

**Comment by Blank-c** [comment]
So do I but I don't think anything is wrong with providing a precompiled bootloader. My compiled pyinstaller (which is used many times with the grabber) still gives less than 5 detection (sometimes 0) for normal programs compiled on my pc. But the same doesn't always happen when I compile the same program with same pyinstaller on another PC. I guess the detectiond are also based on the hardware that they are compiled in.

**Comment by KDot227** [comment]
> So do I but I don't think anything is wrong with providing a precompiled bootloader. My compiled pyinstaller (which is used many times with the grabber) still gives less than 5 detection (sometimes 0) for normal programs compiled on my pc. But the same doesn't always happen when I compile the same program with same pyinstaller on another PC. I guess the detectiond are also based on the hardware that they are compiled in.

I just looked and say that your using the actual pyinstaller off the GitHub. U might be 100% right and it might be better than the pip package but from what I know, the bootloader is the best if you don't want false detections.

**Comment by Smug246** [comment]
gonna close this because i noted all stuff u said kdot
