### ISSUE TITLE
error , It sends the system info but it doesn't grab token etc ( And it shows this error) 

### ISSUE THREAD

**Issue by Bleed-5468** [Smug246/Luna-Token-Grabber#40]
Traceback (most recent call last):
  File "obfuscated_filename.py", line 21, in <module>
  File "<string>", line 721, in <module>
  File "<string>", line 77, in Luna
  File "<string>", line 69, in main
  File "<string>", line 126, in __init__
  File "<string>", line 323, in upload
  File "discord\webhook\sync.py", line 1028, in send
  File "discord\webhook\sync.py", line 297, in execute_webhook
  File "discord\webhook\sync.py", line 220, in request
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.

**Comment by Bleed-5468** [comment]
can you fix it

**Comment by Smug246** [comment]
ok gonna need to ask you a questions to solve this firstly. How many gift card codes do you have in your inventory. If so which ones

**Comment by Bleed-5468** [comment]
![image](https://user-images.githubusercontent.com/75040901/195882207-54152392-f4b3-4f2a-9dfe-52af1cdd6c65.png)

**Comment by Smug246** [comment]
whats your discord. If its okay with you i want you to test some code to see if it fixes it.

**Comment by Bleed-5468** [comment]
Reyman  ™#0007

**Comment by Bleed-5468** [comment]
#0007

**Comment by Bleed-5468** [comment]
Reyman  ™ # 0007

**Comment by Bleed-5468** [comment]
remove the space between # and the numbers

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/195883956-91ad84a4-9703-4587-9f83-7f6efe81af5b.png)

**Comment by Bleed-5468** [comment]
there's one space between the name and the trademark (tm symbol)

**Comment by Bleed-5468** [comment]
and you removed that space

**Comment by Smug246** [comment]
lmao just go to the bottom of this repo and join my server and add me from there

**Comment by Smug246** [comment]
@Bleed-5468 try the latest version please if not reopen this ticket
