### ISSUE TITLE
exe not making

### ISSUE THREAD

**Issue by Bodeyibl** [Smug246/Luna-Token-Grabber#5]
hi, its very good, it only makes no exe, i need pyinstaller to make a exe my self. thats a little waste but can you look afther this?
greetings.

**Comment by Bodeyibl** [comment]
i just edited ''icon'' in here and it works

python -m PyInstaller --onefile --noconsole -i NONE --distpath

**Comment by Smug246** [comment]
thats in the code so there would've been an error when isntalling
