### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by Official-DarianDev** [Smug246/Luna-Token-Grabber#50]
my "clients" get a error during startup with "luna compressed" and the temp "luna logged" file

<3

**Comment by Smug246** [comment]
can u send the error?

**Comment by Official-DarianDev** [comment]
![image](https://user-images.githubusercontent.com/116446349/198134242-12ebea64-3c59-4165-9ab1-4d106ec7ce1e.png)

**Comment by Official-DarianDev** [comment]
also its detected by microsoft. can you make it undetected for Microsoft, or something? because its a bit sussy telling them to turn off av

**Comment by Smug246** [comment]
latest version

**Comment by Blank-c** [comment]
> also its detected by microsoft. can you make it undetected for Microsoft, or something? because its a bit sussy telling them to turn off av

Try: https://github.com/Blank-c/Blankrypt

No advertisements, I just need testers.

**Comment by Smug246** [comment]
> > also its detected by microsoft. can you make it undetected for Microsoft, or something? because its a bit sussy telling them to turn off av
> 
> 
> 
> Try: https://github.com/Blank-c/Blankrypt
> 
> 
> 
> No advertisements, I just need testers.

if you release the sec i'll use it. i'm not gonna use publish something that's not open

**Comment by Blank-c** [comment]
> > > also its detected by microsoft. can you make it undetected for Microsoft, or something? because its a bit sussy telling them to turn off av
> > 
> > 
> > Try: https://github.com/Blank-c/Blankrypt
> > No advertisements, I just need testers.
> 
> if you release the sec i'll use it. i'm not gonna use publish something that's not open

Ye, I am going to open it soon

**Comment by Official-DarianDev** [comment]
kk

**Comment by Smug246** [comment]
> @Smug246 check it out.

https://github.com/Blank-c/Blankrypt/issues/2

**Comment by Smug246** [comment]
think this is fixed
