### ISSUE TITLE
I've got a question

### ISSUE THREAD

**Issue by ReymanMVP** [Smug246/Luna-Token-Grabber#53]
![image](https://user-images.githubusercontent.com/75040901/200116841-ca487af4-cd01-4519-95a2-6c158b0f9715.png)
how does this works? where does it send the nitro etc...?

**Comment by Smug246** [comment]
> ![image](https://user-images.githubusercontent.com/75040901/200116841-ca487af4-cd01-4519-95a2-6c158b0f9715.png)
> 
> how does this works? where does it send the nitro etc...?
> 
> 

it will send the nitro to your webhook and auto buy it if ur can
