### ISSUE TITLE
Getting a execution error

### ISSUE THREAD

**Issue by SilentBloody** [Smug246/Luna-Token-Grabber#58]
Im still pretty new to this but im getting this error when running the .exe:
Traceback (most recent call last):
  File "obfuscated_compressed_TEST.py", line 21, in <module>
  File "<string>", line 1, in <module>
  File "wsnzncqyjpwlbjh", line 20, in <module>
ModuleNotFoundError: No module named 'Crypto'

i feel like im dumb and im missing some things

**Comment by Smug246** [comment]
no ur not doing anything wrong. im not quite sure tbh ill look into it. maybe try deleting the crypto module in case its messing it up. doubt it will fix it

**Comment by Smug246** [comment]
make sure you have latest version of pyinstaller and try latest update

**Comment by SilentBloody** [comment]
> 

i have ver 5.6.2
