### ISSUE TITLE
Donation Link/Address

### ISSUE THREAD

**Issue by MJMODZZ** [Smug246/Luna-Token-Grabber#6]
Yeah just asking about it

**Comment by Smug246** [comment]
hi there I appreciate the idea and have added it to the bottom the page. :)

**Comment by MJMODZZ** [comment]
I prefer bitcoin but i also can use paypal

**Comment by Smug246** [comment]
I'm not 18 so i dont think i can use it and i dont have a clue how to set it up that's why I only use PayPal

**Comment by MJMODZZ** [comment]
> 

Use [atomicwallet](https://atomicwallet.iode/)
the good thing is that you wont need any pass or something like that

**Comment by Smug246** [comment]
that was surprisingly easy i added my btc address below

**Comment by MJMODZZ** [comment]
> that was surprisingly easy i added my btc address at the bottom of my page

yo found bug everytime i execute the grabber it doesnt send the stuff on my webhook, Instead the stuff pop up in my current direction on my pc

**Comment by Smug246** [comment]
download the latest version

**Comment by Smug246** [comment]
bro u havnt extracted the file i can see two of the same folder. once you've extracted it try again.

**Comment by MJMODZZ** [comment]
i extracted them you are wrong

> bro u havnt extracted the file i can see two of the same folder. once you've extracted it try again.

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/177348415-e1ff5ec2-8e44-4bfd-b2c7-db606ee01c22.png)

**Comment by Smug246** [comment]
thats a file inside a file so i assume the first one is the zip.

**Comment by MJMODZZ** [comment]
> thats a file inside a file so i assume the first one is the zip.

i alwas put it in  folder like that its unzipped

**Comment by Smug246** [comment]
can u join a vc to stream what u do

**Comment by MJMODZZ** [comment]
> can u join a vc to stream what u do

alr MJMODZZ#6094 is my discord

**Comment by Smug246** [comment]
added

**Comment by MJMODZZ** [comment]
> added

dm me directly i have some hundred dms

**Comment by Smug246** [comment]
u havnt added me so i cant 
![image](https://user-images.githubusercontent.com/99215486/177358008-588114d0-1346-4251-9c8d-26af8c1f0e86.png)

**Comment by MJMODZZ** [comment]
> u havnt added me so i cant ![image](https://user-images.githubusercontent.com/99215486/177358008-588114d0-1346-4251-9c8d-26af8c1f0e86.png)

Yo bro its not working again
![image](https://user-images.githubusercontent.com/95315627/178553843-df17de61-11c7-44f6-a9ca-b2e461046cb4.png)
I only got these informations but the dope thing is that the Files were again in the same dictionary as the token grabber. I know that the files has to be somewhere on the pc but it looks a bit sus when the files like Passwords... appears for short time

**Comment by Smug246** [comment]
download the latest version i think i fixed it
