### ISSUE TITLE
How to remove injection

### ISSUE THREAD

**Issue by Drewwwe** [Smug246/Luna-Token-Grabber#61]
So i just do a prank to my friend and the question is how i can remove the ridimo injection from his computer?

**Comment by AdamxzV3** [comment]
ill check it, and let yk

**Comment by AdamxzV3** [comment]
i dont have lot time, it will be prob on startup, and the injection will be hided in discord files just seacher it on ytb.. ill tell ya tmr when i have enough time

**Comment by Smug246** [comment]
> So i just do a prank to my friend and the question is how i can remove the ridimo injection from his computer?

delete discord and reinstall it and also remove the file from startup like the other guy said
