### ISSUE TITLE
help with token logging

### ISSUE THREAD

**Issue by The-guide-00** [Smug246/Luna-Token-Grabber#62]
hi, i just wanted to ask what i should do if i run the script but dont have a discord token sent back to me, i have stuff like browser passwords sent back (which i think is awesome), but i just wanted to know if there are any tips anyone could give me regarding getting token logging to work? for me the token file is just blank

**Comment by Smug246** [comment]
im not too sure tbh with you. do you get any error because it works fine for me and most people. its most likely to do with something on your end

**Comment by Smug246** [comment]
no answer so closing
