### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by cdworld0** [Smug246/Luna-Token-Grabber#65]
when i try to download it just says that it is virus :(

**Comment by cdworld0** [comment]
oh thanks dude but it does not send the info to my discord server? and ya i used a working webhook

**Comment by Smug246** [comment]
any errors and what are u testing it on

**Comment by cdworld0** [comment]
whats your discord?

**Comment by gaelxir** [comment]
smug are a tutorial of luna token grabber?

**Comment by Smug246** [comment]
theres a setup but im gonna be making a discord server soon which u can join via my github profile
