### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by HusIter** [Smug246/Luna-Token-Grabber#67]
whenever i click build no exe appers

**Comment by Smug246** [comment]
any error?

**Comment by HusIter** [comment]
no it dos no like give the exe

**Comment by Smug246** [comment]
turn ur antivirus off and try build it

**Comment by HusIter** [comment]
i did and dos windows defender detect the exe

**Comment by Smug246** [comment]
probs, i havnt tested recently

**Comment by HusIter** [comment]
could you make it undetected

**Comment by Smug246** [comment]
nah thats pretty hard and i wouldnt do it for free either
