### ISSUE TITLE
icon doesnt work 

### ISSUE THREAD

**Issue by RDisOP** [Smug246/Luna-Token-Grabber#68]
idk for some reason icon just doesnt show up after compiling the exe   also is there any discord server for this?

**Comment by Smug246** [comment]
i think its because of the crypter ill test it later [discord server here](https://discord.gg/MtjAmEGT)

**Comment by folkdragon** [comment]
> i think its because of the crypter ill test it later [discord server here](https://discord.gg/MtjAmEGT)

discord link is invalid can u give permanent one here

**Comment by Smug246** [comment]
https://discord.gg/Cdyes9Rxtk

**Comment by Smug246** [comment]
sorted
