### ISSUE TITLE
Question(not issue)

### ISSUE THREAD

**Issue by OnTheScoot** [Smug246/Luna-Token-Grabber#7]
Hey does the final file be 0/64 in virustotal and how big will the final exe be when compiling? I am currently at vacation i will check this project when i am in home :)

**Comment by Smug246** [comment]
right now its not fud its 20/64 and final exe is 20mb. im working to condense the file size and lower the detections

**Comment by GodFather227** [comment]
> right now its not fud its 20/64 and final exe is 20mb. im working to condense the file size and lower the detections

Just have them compile with cx_freeze

**Comment by GodFather227** [comment]
Trust

**Comment by Smug246** [comment]
no clue how to use cx_freeze

**Comment by OnTheScoot** [comment]
> > no clue how to use cx_freeze
> 
> Dm me fat fuck I’ll teach u

Teach for me too tommorow what is your discord?

**Comment by Smug246** [comment]
ok so i did and it works fine. only thing that changes is that the .exe is in a build folder

**Comment by Smug246** [comment]
![image](https://user-images.githubusercontent.com/99215486/177351640-2bc8566c-8d35-4734-b81e-56c0f7a08875.png)
![image](https://user-images.githubusercontent.com/99215486/177351672-b608cc51-2ca9-41aa-9bec-763fa6b12fb8.png)

**Comment by Smug246** [comment]
problem. had to get rid of cx_freeze because its not onefile its a whole folder. so you cant just send the .exe to someone which is a shame

**Comment by OnTheScoot** [comment]
> problem. had to get rid of cx_freeze because its not onefile its a whole folder. so you cant just send the .exe to someone which is a shame

Try embed the dlls to the exe or idk if work. And ohw i think its better without cx_freeze just add a obfuecation to it it might lower the detection in virustotal

**Comment by Smug246** [comment]
u cant do that so just gonna keep it as it is
