### ISSUE TITLE
No exe

### ISSUE THREAD

**Issue by yeeteeyt** [Smug246/Luna-Token-Grabber#70]
Ok, I ran the whole thing, but the terminal just closes. there is no exe and it just outputs a python file. I set it to generate an exe

**Comment by Smug246** [comment]
run the builder.py in cmd and send me the error your getting

**Comment by TheYunDude** [comment]
> run the builder.py in cmd and send me the error your getting

hey, I have the same issue. I run the builder.py file and it gives me options. on the one i type "y" to make it an exe, but after the thing is done instead I get the file but a .py. the file still works but it is not an exe. please help

**Comment by TheYunDude** [comment]
oh i got the error here is image for error code 
![image_2022-12-15_223730004](https://user-images.githubusercontent.com/97200157/208037658-a7ba19c0-491e-4bf0-ada5-5ce64f0484f4.png)
if you cannot see picture here is msg:
Traceback (most recent call last):
  File "C:\Users\workforce\Downloads\Luna-Token-Grabber-main\builder.py", line 351, in <module>
    Builder()
  File "C:\Users\workforce\Downloads\Luna-Token-Grabber-main\builder.py", line 71, in __init__
    self.mk_file(self.filename, self.webhook)
  File "C:\Users\workforce\Downloads\Luna-Token-Grabber-main\builder.py", line 267, in mk_file
    self.exe_crypt(f"obfuscated_compressed_{filename}")
  File "C:\Users\workforce\Downloads\Luna-Token-Grabber-main\builder.py", line 295, in exe_crypt
    subprocess.run(["./tools/Blankrypt.exe", f"{filename}.exe"], capture_output=True, check=True)
  File "C:\Users\workforce\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./tools/Blankrypt.exe', 'obfuscated_compressed_thepythoncalculatorclient.exe']' returned non-zero exit status 1.

**Comment by Smug246** [comment]
lmao read the top. it says 'python not found' you need to download the latest version of python and add it to path.

**Comment by TheYunDude** [comment]
> lmao read the top. it says 'python not found' you need to download the latest version of python and add it to path.

oh damn just remembered i got python 3.9 for another client. thanks i will try it

**Comment by TheYunDude** [comment]
same thing happened, and i have python 3.11.1, i think it is because i cannot run files with "python" but with "py" instead
example: if i do "python main.py" it wont work
but if i do "py main.py" it will work.
maybe thats the problem but how do i fix the issue
btw i did add it to path

**Comment by TheYunDude** [comment]
my discord is sunuy#7832 if its easier to type there

**Comment by Smug246** [comment]
join my server and dm me from there. but python main.py and py main.py are no different. also delete 3.9 in case it uses that instead of 3.11
