### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xionerme** [Smug246/Luna-Token-Grabber#71]
![image](https://user-images.githubusercontent.com/72628690/207027558-494ddaaf-f04b-400c-ab4a-3a21f5e3cd20.png)

wtf?

**Comment by Xionerme** [comment]
or this 
![image](https://user-images.githubusercontent.com/72628690/207029907-f94d9a4f-ffaa-4da6-9d16-132c9953ee37.png)

**Comment by Smug246** [comment]
have you got latest version of python and i can't read russian either
