### ISSUE TITLE
this is a virus

### ISSUE THREAD

**Issue by Ruhf22** [Smug246/Luna-Token-Grabber#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Smug246** [comment]
bruh what

**Comment by Smug246** [comment]
its open source

**Comment by Official-DarianDev** [comment]
ikr, its clean

**Comment by NCPUser** [comment]
stealer :fox:

**Comment by Smug246** [comment]
closing because this is stupid
