### ISSUE TITLE
better webhook protection

### ISSUE THREAD

**Issue by godlysaint** [Smug246/Luna-Token-Grabber#75]
My discord webhook got spammed and deleted, could you possibly add some better protection against that? I love your shit tho tysm

**Comment by Smug246** [comment]
the obfuscation i use is mainly to  confuse the average person. anyone  that knows basic python knows how to deobfuscate the code. yes i can improve the obfuscation but at the end of the day it can always be reversed to its original source because python is an interpreted language

**Comment by TheYunDude** [comment]
if you really want to, you can obfuscate the file yourself

**Comment by Smug246** [comment]
improved due to new blank obf update
