### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Rdmo2** [Smug246/Luna-Token-Grabber#76]
hey so, I put the grabbers code into another project and tried something, when I try to obfuscate it now I only got this error:

```
Traceback (most recent call last):
  File "C:\Users\...\Downloads\Python-Compressor-main\File_Compressor.py", line 30, in <module>
    setup()
  File "C:\Users\...\Downloads\Python-Compressor-main\File_Compressor.py", line 16, in setup
    a = str(file_to_obfuscate_open.read())
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2239: character maps to <undefined>
```

I tried 5 different obfuscators

add one and please help
Payload#1085
Rdimo#1263

**Comment by Rdmo2** [comment]
btw how do you make the pictures int he readme of this project and censor them and add these special edges

**Comment by Smug246** [comment]
so for your obfuscation problem most obfuscators can't decode some characters in the script. Secondly i use a program for those edges and same for the blur

**Comment by Rdmo2** [comment]
and how do I fix this? may you also tell me what is this porgram called?

> so for your obfuscation problem most obfuscators can't decode some characters in the script. Secondly i use a program for those edges and same for the blur
