### ISSUE TITLE
cookie send

### ISSUE THREAD

**Issue by hiro1434** [Smug246/Luna-Token-Grabber#77]
The token grabber does not send cookies from other Google Chrome profiles

**Comment by Smug246** [comment]
how do yk because there all bunched up together

**Comment by hiro1434** [comment]
Now, is it possible to have another file for each profile?

**Comment by Smug246** [comment]
i guess ye it could be but kinda impractical. if your looking for something in particular just press  ctrl + f and type what ur looking for and it will find it
