### ISSUE TITLE
Can't run build.bat

### ISSUE THREAD

**Issue by Milloper** [Smug246/Luna-Token-Grabber#8]
I have already installed all the required modules
Whenever I start "Build.bat" I get this error:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 209, in <module>
    Builder()
  File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 16, in __init__
    self.loading()
  File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 99, in loading
    IP: {load(urlopen('https://jsonip.com/'))['ip']}
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Comment by MJMODZZ** [comment]
> I have already installed all the required modules Whenever I start "Build.bat" I get this error:
> 
> Traceback (most recent call last): File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open h.request(req.get_method(), req.selector, req.data, headers, File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request self._send_request(method, url, body, headers, encode_chunked) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output self.send(msg) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send self.connect() File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1447, in connect super().connect() File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 941, in connect self.sock = self._create_connection( File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\socket.py", line 824, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 11004] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 209, in Builder() File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 16, in **init** self.loading() File "C:\Users\User\Downloads\Luna-Token-Grabber-main\builder.py", line 99, in loading IP: {load(urlopen('[https://jsonip.com/'))['ip']}](https://jsonip.com/'))%5B'ip'%5D%7D) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen return opener.open(url, data, timeout) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open response = self._open(req, data) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open result = self._call_chain(self.handle_open, protocol, protocol + File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain result = func(*args) File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open return self.do_open(http.client.HTTPSConnection, req, File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open raise URLError(err) urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

Make sure to have the Newst Version of [Python](https://www.python.org/ftp/python/3.10.5/python-3.10.5-amd64.exe) Installed and **DONT** use the Microsoft Store version. When you are installing, Make sure you enable 

- [x] Add Python 3.10.5 to Path.

After that install the requirements with the [installer.bat](https://github.com/Smug246/Luna-Token-Grabber/blob/main/installer.bat)

and open the [Builder.py](https://github.com/Smug246/Luna-Token-Grabber/blob/main/builder.py)

**Comment by Smug246** [comment]
ye what he said ^^^^

**Comment by Milloper** [comment]
Python is not the Microsoft Store version and it's the 3.10.5,
My current environment variable for PATH is:
C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\
C:\Users\User\AppData\Local\Programs\Python\Python310\
I also checked the " Add Python 3.10.5 to Path." during the installation

**Comment by Milloper** [comment]
All requirements are installed in the folder: "c:\users\user\appdata\local\programs\python\python310\lib\site-packages"

**Comment by Smug246** [comment]
windows firewall may be blocking it and check you don't have a environmental variable in paths named http_proxy. if you do delete it

**Comment by Smug246** [comment]
another thing you could try is paste this https://jsonip.com into the google url on your pc and see what the response is. it should bring up a white page with your ip in the top left.

**Comment by MJMODZZ** [comment]
> I can't access the website, it says "ERR_ADDRESS_INVALID" I have no firewall on but I'm pretty sure it's a problem on my end

Do you use something like a VM or cloud PC?
If you need help you can just join the [Discord](https://discord.gg/luna22) , im MJMODZZ#6094 there and Smug246 is Smug#6469 there, better dm us for that

**Comment by Milloper** [comment]
Oh god I'm a dumbass, for some reason I had jsonip.com on my host file *facepalm*
Everything works correctly now

**Comment by Smug246** [comment]
np it's fine. i'll keep the issue open in case other people get the same problem.

**Comment by addi00000** [comment]
> np it's fine. i'll keep the issue open in case other people get the same problem.

[pin](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) rather than remain open
