### ISSUE TITLE
No python detected bug

### ISSUE THREAD

**Issue by ilikebeingbuttfucked** [Smug246/Luna-Token-Grabber#82]
It claims that it can't find python. I have python installed and added to PATH, I tried uninstalling it and reinstalling it yet the same thing occurred. I cannot get a screenshot, it happens so fast.

**Comment by Smug246** [comment]
did u install python from the website and not microsoft store

**Comment by ilikebeingbuttfucked** [comment]
yeah i did

**Comment by Smug246** [comment]
do u have a different version of python that may be interferring

**Comment by TheYunDude** [comment]
just quickly check again if you have python downloaded from microsoft store, if you dont there still might be an error. Search up how to delete python from microsoft store using cmd.. the download for microsoft store could have failed but there could still be an issue

**Comment by Blank-c** [comment]
This ain't at "bug", its just your python copy is corrupt or not installed. You can check this by quickly typing `python --version` in cmd. If it shows the same error, its clear that its not installed. You can uninstall python from the control panel. While installing a new copy of python, make sure you select the `Add to PATH` option in the setup's startup.

**Comment by Smug246** [comment]
closing because no response
