### ISSUE TITLE
probably doing something wrong, maybe not. 

### ISSUE THREAD

**Issue by michelleguetonal** [Smug246/Luna-Token-Grabber#83]
i get this after building the exe. 

Traceback (most recent call last):
  File "game.py", line 1, in <module>
  File "<string>", line 4, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'ctypes'
![image](https://user-images.githubusercontent.com/113273256/210259807-81468dcc-9447-4bc2-8707-9b123db9f9ea.png)

**Comment by Smug246** [comment]
ahh i need to add hidden module imports

**Comment by michelleguetonal** [comment]
thanks daddy <3
please reply to this comment when you have added it

**Comment by michelleguetonal** [comment]
also is there hidden python install if the victim doesn't have python already?

**Comment by Smug246** [comment]
no its only when building it. try latest version

**Comment by michelleguetonal** [comment]
![image](https://user-images.githubusercontent.com/113273256/210264868-df8c0ad3-d180-48a8-bdd2-8025e00b10d6.png)
This appears after using the .exe and the webhook only gives the logged zip

**Comment by Smug246** [comment]
this should be fixed in latest version

**Comment by michelleguetonal** [comment]
thanks dad
