### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xHaruke** [Smug246/Luna-Token-Grabber#86]
**Describe the bug**
![image](https://user-images.githubusercontent.com/87328375/210940415-23785535-475b-49c8-8453-3d944d324fb3.png)

**To Reproduce**
1.Build the app with everything except the fake error on
2. Run the exe 
![image](https://user-images.githubusercontent.com/87328375/210940396-34cd0101-df32-4a99-920e-8d7194640249.png)

**Comment by Smug246** [comment]
add a webhook lmao. press check webhook

**Comment by Smug246** [comment]
no answer

**Comment by xHaruke** [comment]
> add a webhook lmao. press check webhook

lmao as if i didnt do that
