### ISSUE TITLE
[FEATURE Requests) Better Injection + Autofill data + Better zip format

### ISSUE THREAD

**Issue by ghost** [Smug246/Luna-Token-Grabber#87]
**Better Injection**
Add 2fa injection (eg, when someone enables 2fa it'll send the 2fa totp key)
Add CC injection (eg, when someone adds a new credit card to his account it'll get the credit card infos such as full name + address + cvc code + cc date + cc number)

**Better stealer**
Add browser autofill data stealer
Add telegram session stealer

**Better UI**
When it sends data to the webhook it flags passwords in a design like this

*Financial passwords :*
paypal
amazon
*Email passwords*
Proton.me
Gmail
Outlook
*Social medias passwords :*
Instagram
Twitter
Youtube
*Services*
Mediafire
Mega.nz
ChatGPT

**Add exodus and metamask stealer**

**Make better zip format**
Browsers >
*Edge* >
Users >
User 1 >
passwords.txt
autofill.txt
cc.txt
cookies.txt
*Chrome* >
Users >
User 1 >
passwords.txt
autofill.txt
cc.txt
*Firefox* >
Users >
User 1 >
passwords.txt
autofill.txt
cc.txt

Tokens >
discord_app_tokens.txt
chrometokens.txt

Others >
deviceinfos.txt
ipaddress.txt

**Comment by Smug246** [comment]
i think some of these are a bit overkill like ipaddress.txt but some good ideas here. Question however, what do you actually want from the wallets such as exodus

**Comment by Smug246** [comment]
so i made the format different like you asked however it makes the runtime 4-8 seconds longer. if you guys are okay with this lmk

**Comment by Smug246** [comment]
changed the file format and no further comments for the other stuff
