### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by ScriptArmy** [Smug246/Luna-Token-Grabber#88]
**Describe the bug**
When I properly entered the webhook and then builded this error appeared.

**To Reproduce**
1. Extract zip
2. Open setup.bat
3. Run builder.py
4. Check everything except disable windows defender
5. Do the file extensions and webhook
6. See error

**Expected behavior**
Probably because of the webhook or no admin perms?

**Screenshots**
![image](https://user-images.githubusercontent.com/62745468/211190456-c5ab50f5-9888-4104-8111-6f4dd028ea83.png)

**Comment by ScriptArmy** [comment]
fixed

**Comment by Smug246** [comment]
okay
