### ISSUE TITLE
i donwloaded all the things i needed and keep getting an error when i try to build an exe (NOT WHEN I DO PYTHON)

### ISSUE THREAD

**Issue by InterMeT0** [Smug246/Luna-Token-Grabber#89]
Command '['python', '-m', 'PyInstaller', '--onefile', '--clean', '--noconsole', '--upx-dir=./tools', '--distpath', './', '--hidden-import', 'base64', '--hidden-import', 'ctypes', '--hidden-import', 'json', '--hidden-import', 'os', '--hidden-import', 'platform', '--hidden-import', 'random', '--hidden-import', 're', '--hidden-import', 'sqlite3', '--hidden-import', 'subprocess', '--hidden-import', 'sys', '--hidden-import', 'threading', '--hidden-import', 'uuid', '--hidden-import', 'shutil.copy2', '--hidden-import', 'argv', '--hidden-import', 'tempfile.gettempdir', '--hidden-import', 'tempfile.mkdtemp', '--hidden-import', 'zipfile.ZIP_DEFLATED', '--hidden-import', 'zipfile.ZipFile', '--hidden-import', 'psutil', '--hidden-import', 'requests', '--hidden-import', 'wmi', '--hidden-import', 'Crypto.Cipher.AES', '--hidden-import', 'discord', '--hidden-import', 'discord.Embed', '--hidden-import', 'discord.File', '--hidden-import', 'discord.SyncWebhook', '--hidden-import', 'PIL', '--hidden-import', 'PIL.ImageGrab', '--hidden-import', 'win32crypt', '--hidden-import', 'win32crypt.CryptUnprotectData', '--icon', 'C:\\Users\\User\\Desktop\\Luna\\icon.ico', '.\\game.py']' returned non-zero exit status 1.

this is the error i keep getting any1 know a fix?

**Comment by InterMeT0** [comment]
@Smug246

**Comment by Smug246** [comment]
i answered this on my discord server
