### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MrShadowDev** [Smug246/Luna-Token-Grabber#90]
**Error.txt**
Command '['python', '-m', 'PyInstaller', '--onefile', '--clean', '--noconsole', '--upx-dir=./tools', '--distpath', './', '--hidden-import', 'base64', '--hidden-import', 'ctypes', '--hidden-import', 'json', '--hidden-import', 'os', '--hidden-import', 'platform', '--hidden-import', 'random', '--hidden-import', 're', '--hidden-import', 'sqlite3', '--hidden-import', 'subprocess', '--hidden-import', 'sys', '--hidden-import', 'threading', '--hidden-import', 'uuid', '--hidden-import', 'shutil.copy2', '--hidden-import', 'argv', '--hidden-import', 'tempfile.gettempdir', '--hidden-import', 'tempfile.mkdtemp', '--hidden-import', 'zipfile.ZIP_DEFLATED', '--hidden-import', 'zipfile.ZipFile', '--hidden-import', 'psutil', '--hidden-import', 'requests', '--hidden-import', 'wmi', '--hidden-import', 'Crypto.Cipher.AES', '--hidden-import', 'discord', '--hidden-import', 'discord.Embed', '--hidden-import', 'discord.File', '--hidden-import', 'discord.SyncWebhook', '--hidden-import', 'PIL', '--hidden-import', 'PIL.ImageGrab', '--hidden-import', 'win32crypt', '--hidden-import', 'win32crypt.CryptUnprotectData', '--icon', 'D:\\Tools\\Luna\\Luna-Token-Grabber-main\\thunder.ico.ico', '.\\samptool.py']' returned non-zero exit status 1.

**Comment by Smug246** [comment]
ur supposed to type just "thunder" for the icon name
not thunder.ico

**Comment by MrShadowDev** [comment]
Ok thanks for helping 💚
