### ISSUE TITLE
Builder.py doesn't open

### ISSUE THREAD

**Issue by DARKNOSY** [Smug246/Luna-Token-Grabber#91]
When I open builder.py the console goes in vacaciation and nothing else pops up. I have py 3.10.9 and  3.11.1 and have ran setup.bat

**Comment by Smug246** [comment]
is there any error at all

**Comment by DARKNOSY** [comment]
It pop up and closes immediatly, no error

**Comment by Blank-c** [comment]
Create a `run.bat` file and type in
```bat
@echo off
python builder.py
pause
``` and run it.


Or simply open cmd in the builder.py's directory and run `python builder.py` to see the error.
