### ISSUE TITLE
auto close issue

### ISSUE THREAD

**Issue by godisreal1** [Smug246/Luna-Token-Grabber#92]
**Describe the bug**
When I open setup.bat it just autocloses, when I open builder.py it just autocloses and theres also two builder.py both of them autoclose

**To Reproduce**
1. Go to setup.bat, it autocloses for me then click builder. py both of them they both autoclose, and no gui pops up.

**Expected behavior**
I expected the gui to pop up

please help

**Comment by Smug246** [comment]
join my server and go to the #help channel and theres a tutorial of how to see the error ur getting https://discord.gg/UYz7yfmS

**Comment by Blank-c** [comment]
Do you have python installed? Open command prompt and type `python --version`

**Comment by Smug246** [comment]
no further comments
