### ISSUE TITLE
Windows 11 Bug

### ISSUE THREAD

**Issue by lux-206** [Smug246/Luna-Token-Grabber#93]
On Windows 11 luna is having issue getting ppls cookies password and history and in the windows version it says "Windows-10-10.0.22621-SP0"

To Reproduce the bug just exec luna in a windows 11 machine

Screenshots
the screenshot of the person pc
![image](https://user-images.githubusercontent.com/98544523/212447128-99997e42-fa41-4b2d-a1b1-d6ddcc46fd42.png)
Win version
![image](https://user-images.githubusercontent.com/98544523/212447118-898cc0d0-5b23-4838-89a6-287e970aac9b.png)
Cookies grabbed
![image](https://user-images.githubusercontent.com/98544523/212447111-f4439459-c27b-4dbf-9b81-ee6a5feadc61.png)

**Comment by Smug246** [comment]
is that why you want opera browser added?

**Comment by Smug246** [comment]
no further comments and added opera stealing
