### ISSUE TITLE
Builder.py auto close

### ISSUE THREAD

**Issue by Appolon24800** [Smug246/Luna-Token-Grabber#95]
When i open "Builder.py" (after opened setup.bat) its crash

![image](https://user-images.githubusercontent.com/93398824/212552011-cc350973-4df9-4408-9ce7-dc28afa3f285.png)

i have a error and i try to redownload and still don't work :/
i have python 3.11

**Comment by Appolon24800** [comment]
work but ... 
![image](https://user-images.githubusercontent.com/93398824/212552346-da79c8c5-c128-4572-8785-40157e6f7a41.png)

**Comment by Smug246** [comment]
sorry. use builder.pyw. and people keep getting that error. i'm not sure exactly why yet but i think its something to with the way the webhook gets added

**Comment by Smug246** [comment]
press check webhook twice before building it

**Comment by Blank-c** [comment]
> work but ... ![image](https://user-images.githubusercontent.com/93398824/212552346-da79c8c5-c128-4572-8785-40157e6f7a41.png)

When does this error pops up?
